package com.app.dubovozkiapp.ui.theme

import androidx.compose.ui.graphics.Color

val dubkiLightPrimary = Color(0xFF825500)
val dubkiLightOnPrimary = Color(0xFFFFFFFF)
val dubkiLightPrimaryContainer = Color(0xFFFFDDAE)
val dubkiLightOnPrimaryContainer = Color(0xFF2A1800)
val dubkiLightSecondary = Color(0xFF6F5B40)
val dubkiLightOnSecondary = Color(0xFFFFFFFF)
val dubkiLightSecondaryContainer = Color(0xFFFADEBC)
val dubkiLightOnSecondaryContainer = Color(0xFF271904)
val dubkiLightTertiary = Color(0xFF9FBD39)
val dubkiLightOnTertiary = Color(0xFFFFFFFF)
val dubkiLightTertiaryContainer = Color(0xFFD3EABC)
val dubkiLightOnTertiaryContainer = Color(0xFF102004)
val dubkiLightError = Color(0xFFBA1B1B)
val dubkiLightErrorContainer = Color(0xFFFFDAD4)
val dubkiLightOnError = Color(0xFFFFFFFF)
val dubkiLightOnErrorContainer = Color(0xFF410001)
val dubkiLightBackground = Color(0xFFFCFCFC)
val dubkiLightOnBackground = Color(0xFF1F1B16)
val dubkiLightSurface = Color(0xFFFCFCFC)
val dubkiLightOnSurface = Color(0xFF1F1B16)
val dubkiLightSurfaceVariant = Color(0xFFF0E0CF)
val dubkiLightOnSurfaceVariant = Color(0xFF4F4539)
val dubkiLightOutline = Color(0xFF817567)
val dubkiLightInverseOnSurface = Color(0xFFF9EFE6)
val dubkiLightInverseSurface = Color(0xFF34302A)
val dubkiLightPrimaryInverse = Color(0xFF3191D3)

val dubkiDarkPrimary = Color(0xFFFFB945)
val dubkiDarkOnPrimary = Color(0xFF452B00)
val dubkiDarkPrimaryContainer = Color(0xFF624000)
val dubkiDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val dubkiDarkSecondary = Color(0xFFDDC3A2)
val dubkiDarkOnSecondary = Color(0xFF3E2E16)
val dubkiDarkSecondaryContainer = Color(0xFF56442B)
val dubkiDarkOnSecondaryContainer = Color(0xFFFADEBC)
val dubkiDarkTertiary = Color(0xFF88A81F)
val dubkiDarkOnTertiary = Color(0xFF243516)
val dubkiDarkTertiaryContainer = Color(0xFF3A4C2B)
val dubkiDarkOnTertiaryContainer = Color(0xFFD3EABC)
val dubkiDarkError = Color(0xFFFFB4A9)
val dubkiDarkErrorContainer = Color(0xFF930006)
val dubkiDarkOnError = Color(0xFF680003)
val dubkiDarkOnErrorContainer = Color(0xFFFFDAD4)
val dubkiDarkBackground = Color(0xFF1F1B16)
val dubkiDarkOnBackground = Color(0xFFEAE1D9)
val dubkiDarkSurface = Color(0xFF1F1B16)
val dubkiDarkOnSurface = Color(0xFFEAE1D9)
val dubkiDarkSurfaceVariant = Color(0xFF4F4539)
val dubkiDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val dubkiDarkOutline = Color(0xFF9C8F80)
val dubkiDarkInverseOnSurface = Color(0xFF32281A)
val dubkiDarkInverseSurface = Color(0xFFEAE1D9)
val dubkiDarkPrimaryInverse = Color(0xFF277AB1)